spring.application.name=mindflow-backend

# База данных
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/mindflow_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${APP_JWT_SECRET:mindflow_super_secret_key_256_bit_long_string_here_abc123}
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

# Server
server.port=${SERVER_PORT:8081}

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html